name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  allPackages:
    runs-on: ubuntu-latest
    env:
      cancelJob: false
    strategy:
      fail-fast: false
      matrix:
        pkgName:
#          - zaread
          - holehe-git
 #         - libxft-bgra
        aurDeps:
 #         - ''
          - 1
 #         - ''
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Check modified files
        run: |
          git diff --name-only HEAD HEAD^ | grep -q "${{ matrix.pkgName }}" || echo "cancelJob=true" >> $GITHUB_ENV
      
      - name: Makepkg build, check and generate .SRCINFO
        if: ${{ env.cancelJob == 'false' }}
        uses: santilococo/pkgbuild-action@master
        with:
          pkgdir: "${{ matrix.pkgName }}"
          aurDeps: "${{ matrix.aurDeps }}"
       
      - name: Push .SRCINFO
        if: ${{ env.cancelJob == 'false' }}
        run: |
          git config --local user.name "$(git log --format=%an | head -n 1)"
          git config --local user.email "$(git log --format=%ae | head -n 1)"
          msg="Update" && [ -f "${{ matrix.pkgName }}/.SRCINFO" ] || msg="Add"
          mv .SRCINFO "${{ matrix.pkgName }}"
          if [ ! -z "$(git status --porcelain)" ]; then
            git add "${{ matrix.pkgName }}/.SRCINFO"
            git pull
            git commit -m "$msg ${{ matrix.pkgName }}/.SRCINFO"
            git push
          fi
       
      - name: Push to AUR
        if: ${{ env.cancelJob == 'false' }}
        run: |
          [ ! -d $HOME/.ssh ] && mkdir -m 0700 $HOME/.ssh
          ssh-keyscan -H aur.archlinux.org > $HOME/.ssh/known_hosts
          echo "${{ secrets.AUR_SSH_KEY }}" > $HOME/.ssh/aur
          chmod 0400 $HOME/.ssh/aur
          ssh-keygen -vy -f $HOME/.ssh/aur -P ${{ secrets.AUR_SSH_PASSPHRASE }} > $HOME/.ssh/aur.pub
          eval $(ssh-agent)
          echo ${{ secrets.AUR_SSH_PASSPHRASE }} | SSH_ASKPASS=/bin/cat SSH_ASKPASS_REQUIRE=force setsid -w ssh-add $HOME/.ssh/aur
          
          msg="$(git log --format=%s | head -n 1)"
          git config --local user.name "$(git log --format=%an | head -n 1)"
          git config --local user.email "$(git log --format=%ae | head -n 1)"
          
          git checkout --orphan ${{ matrix.pkgName }}
          git rm -rf .
          git remote add ${{ matrix.pkgName }} ssh://aur@aur.archlinux.org/${{ matrix.pkgName }}.git
          set +e; git pull ${{ matrix.pkgName }} master; set -e
          git checkout master ${{ matrix.pkgName }}
          mv ${{ matrix.pkgName }}/PKGBUILD .
          mv ${{ matrix.pkgName }}/.SRCINFO .
          rm -rf ${{ matrix.pkgName }}
          if [ ! -z "$(git status --porcelain)" ]; then
            git add .
            msg="Add PKGBUILD and .SRCINFO"
            git commit -m "$msg"
            git push --set-upstream ${{ matrix.pkgName }} ${{ matrix.pkgName }}:master
          fi
