name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  allPackages:
    runs-on: ubuntu-latest
    env:
      cancelJob: false
    strategy:
      fail-fast: false
      matrix:
        pkgName:
          - zaread
          - libxft-bgra
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Check modified files
        run: |
          git diff --name-only HEAD HEAD^ | grep -q "${{ matrix.pkgName }}" || echo "cancelJob=true" >> $GITHUB_ENV

      - name: Build and check pkg
        if: ${{ env.cancelJob == 'false' }}
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: "${{ matrix.pkgName }}"
